site_name: Neuropixel Utilities
site_description: Documentation for neuropixel-utils
site_author: Daniel J. O'Shea

repo_name: 'djoshea/neuropixel-utils'
repo_url: 'https://github.com/djoshea/neuropixel-utils'

theme:
  icon:
    logo: fontawesome/solid/brain
  name: material
  feature:
    - navigation.tabs: false
  palette:
    primary: 'blue'
    accent: 'blue'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/djoshea
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/djoshea'

markdown_extensions:
  - admonition
  - codehilite
  - markdown.extensions.def_list
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - smarty
  - toc:
      permalink: true

nav:
  - Overview: index.md
  - Neuropixel.ImecDataset: imec_dataset.md
  - Running Kilosort: kilosort.md
  - Analysis of Kilosort Results: analysis.md
  - Extracting Waveforms: waveforms.md
  - Acknowledgements and Support: acknowledgements.md

copyright: 'Copyright &copy; 2020 &mdash; <a href="http://djoshea.com">Daniel J. O&#39;Shea</a>'
